# Generated by Django 5.2.5 on 2025-09-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='匿名acab34c94a4f', max_length=30, unique=True),
        ),
    ]
